config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  root 'dashboard#index'

  resources :artists, shallow: true do
    resources :albums
  end

  resources :albums, only: [], shallow: true do
    resources :songs
  end

  resources :songs do
    member do
      post :upvote
      post :downvote
    end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_many :albums, dependent: :destroy
  has_many :songs, through: :albums, dependent: :destroy

  validates :name, presence: true
  validates :origin, presence: true

  has_attached_file :profile_img, styles: { med: "350x350", thumb: "100x100" }
  validates_attachment_content_type :profile_img, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :find_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all.order('id ASC')
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    authorize @artist

    if @artist.save
      flash[:success] = "Artist Created"
      redirect_to @artist
    else
      flash[:error] = "Sorry, We Couldn't Save the Artist"
      render 'new'
    end
  end

  def edit
  end

  def update
    authorize @artist

    if @artist.update(artist_params)
      flash[:success] = "Artist successfully updated"
      redirect_to @artist
    else
      flash[:error] = "Please enter valid values"
      render 'edit'
    end
  end

  def destroy
    authorize @artist
    @artist.destroy
    flash[:succes] = "Artist successfully deleted"
    redirect_to artists_path
  end

  private

  def find_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :bio, :origin, :profile_img)
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
  <%= form_for @artist do |f| %>

  <% if @artist.errors.any? %>
  <div id="errors">
    <h2 class='alert alert-danger'><%= pluralize(@artist.errors.count, 'error') %> stopped this post from saving.</h2>
    <ul>
      <% @artist.errors.full_messages.each do |msg| %>
      <li class='alert alert-info'><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <label for="profile_img">Profile Picture</label>
    <%= f.file_field :profile_img %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control', id: 'artist_name' %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, placeholder: 'Bio', class: 'form-control', id: 'artist_bio' %>
  </div>

  <div class="form-group">
    <%= f.label :origin %>
    <%= f.text_field :origin, placeholder: 'Origin', class: 'form-control', id: 'artist_origin' %>
  </div>

  <div>
    <%= f.submit 'Add Artist', class: 'btn btn-primary' %>
  </div>

  <% end %>

app/views/artists/edit.html.erb
<div class='col-xs-6 col-xs-offset-3'>

  <h1>Edit Artist</h1>

  <%= render 'form' %>
</div>

app/views/artists/index.html.erb
<div class="container">
  <div>
    <% @artists.each do |artist| %>

    <div class='col-md-4', id='artist-index-img'>

      <!-- Links picture to artist page -->
      <%= link_to artist_path(artist) do %>
        <%= image_tag(artist.profile_img.url(:med)) %>
      <% end %>
      <br>
      <br>

      <div class='btn-group' id='artist-index-menu' style='margin: auto;'>
      <%= link_to 'Albums', artist_albums_path(artist), class: 'btn btn-success' %>
      <%= link_to "Create Album", new_artist_album_path(artist), class: 'btn btn-primary' %>
      <%= link_to "Edit", edit_artist_path(artist), class: 'btn btn-info' %>
      <%= link_to "Delete", artist_path(artist), method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>

    <% end %>

  </div>
  <%= link_to 'Create Artist', new_artist_path, class: 'btn btn-default' %>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

app/views/artists/show.html.erb
<div class="artist-profile-bg">
  <img class="artist-profile-bg" src="http://thepaperwall.com/wallpapers/music/big/big_bcd0cf682ac3a3ce331a5de4c63d2e7be46a7970.jpg">
</div>

<!-- The bg im can be a separate image from the profile image and needs to have its own methods/column under artist -->

<div class="container">
  <section>
    <div class="artist-profile">

      <div class="row">
        <div class="col-md-4">
          <div class='artist-profile-img-wrapper'>
            <%= image_tag(@artist.profile_img.url(:med), class: 'artist-profile-img') %>
          </div>
        </div>

        <div class="col-md-8">
          <div class="col-md-4 text-center">
            <h4>Albums</h4>
            <%= @artist.albums.count %>
          </div>
          <div class="col-md-4 text-center">
            <h4>Songs</h4>
            <%= @artist.songs.count %>
          </div>
          <div class="col-md-4 text-center">
            <h4>Rating</h4>
          </div>
        </div>
      </div>

      <div class="artist-profile-text">
        <h1><%= @artist.name %></h1>
        <small><%= @artist.origin %></small>
      </div>

    </div>
  </section>
</div> <!-- /container -->