config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  root 'dashboard#index'

  resources :artists, shallow: true do
    resources :albums
  end

  resources :albums, only: [], shallow: true do
    resources :songs
  end

  resources :songs do
    member do
      post :upvote
      post :downvote
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :artist
  has_many :songs
  has_many :votes, through: :songs do

    # This will count up the total likes amongs all the songs
    def total_likes
      total = 0
      self.each { |vote| total += vote.likes.count }
      total
    end

    def total_dislikes
      total = 0
      self.each { |vote| total += vote.dislikes.count }
      total
    end

    # Tallies the votes
    def total_votes
      total_likes + total_dislikes
    end

    # gives the overall rating percent for album
    def like_percent
      sum = (total_likes/total_votes) * 100
      sum.round(1).to_s + "%"
    end

    def dislike_percent
      sum = (total_likes/total_votes) * 100
      sum.round(1).to_s + "%"
    end

  end

  validates :title, presence: true
  validates :label, presence: true

  after_initialize :ensure_label_has_a_value

  has_attached_file :cover_art, styles: { med: "350x350", thumb: "100x100" }
  validates_attachment_content_type :cover_art, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  private

  # Set only if label IS NOT set
  def ensure_label_has_a_value
    self.label ||= independent
  end

  def independent
    "Independent"
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :find_artist, only: [:index, :new, :create]
  before_action :find_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = @artist.albums.all
  end

  def show
  end

  def new
    @album = @artist.albums.build
  end

  def create
    @album = @artist.albums.create(album_params)
    authorize @album

    if @album.save
      flash[:success] = 'Album successfully created'
      redirect_to artist_albums_path(@artist)
    else
      flash[:error] = "Sorry, the album didn't save"
      render 'new'
    end
  end

  def edit
  end

  def update
    authorize @album
    if @album.update(album_params)
      flash[:success] = "Album successfully updated"
      redirect_to @album
    else
      flash[:error] = "Sorry, the album didn't update"
      render 'edit'
    end
  end

  def destroy
    authorize @album
    @album.destroy

    redirect_to artists_path
  end

  private

  def find_artist
    @artist = Artist.find(params[:artist_id])
  end

  def album_params
    params.require(:album).permit(:title, :label)
  end

  def find_album
    @album = Album.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for album do |f| %>

<% if @album.errors.any? %>
<div id="errors">
  <h2 class='alert alert-danger'><%= pluralize(@album.errors.count, 'error') %> stopped this post from saving.</h2>
  <ul>
    <% @album.errors.full_messages.each do |msg| %>
    <li class='alert alert-info'><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Title', class: 'form-control', id: 'album_title' %>
</div>

<div class="form-group">
  <%= f.label :label %>
  <%= f.text_area :label, placeholder: 'Label', class: 'form-control', id: 'album_label' %>
</div>

<div>
  <%= f.submit 'Add Album', class: 'btn btn-primary' %>
</div>

<% end %>

app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %> </h1>

<%= form_for([@artist, @album]) do |f| %>

<% if @album.errors.any? %>
<div id="errors">
  <h2 class='alert alert-danger'><%= pluralize(@album.errors.count, 'error') %> stopped this post from saving.</h2>
  <ul>
    <% @album.errors.full_messages.each do |msg| %>
    <li class='alert alert-info'><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Title', class: 'form-control', id: 'album_title' %>
</div>

<div class="form-group">
  <%= f.label :label %>
  <%= f.text_area :label, placeholder: 'Label', class: 'form-control', id: 'album_label' %>
</div>

<div>
  <%= f.submit 'Update Album', class: 'btn btn-primary' %>
</div>

<% end %>

app/views/albums/index.html.erb
<h1><%= @artist.name %>'s Albums</h1>

<% @albums.each do |album| %>
  <h3><%= link_to album.title, album_path(album) %></h3>
  <%= link_to 'Edit Album', edit_album_path(album), class: 'btn btn-primary' %>
  <%= link_to 'Delete', album_path(album), method: :delete, class: 'btn btn-danger' %>
<% end %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render partial: 'form', locals: { album: [@artist, @artist.albums.build]} %>

app/views/albums/show.html.erb
<div class="container-fluid">
  <div class='row'>
    <h1>
      <%= @album.title %>
    </h1>
    <small><%= @album.label %></small><br>
  </div>

  <div class='row'>
    <div class="col-md-6">
      <% @album.songs.each do |song| %>
      <table class="table">
        <tr>
          <td><h4><%= song.title %></h4></td>
          <td>
            <%= link_to upvote_song_path(song), method: :post, class: 'btn btn-primary' do %>
            Like <span class='badge'><%= song.vote.likes.count %></span>
            <% end %>
          </td>
          <td>
            <%= link_to downvote_song_path(song), method: :post, class: 'btn btn-danger' do %>
            Dislike <span class='badge'><%= song.vote.dislikes.count %></span>
            <% end %>
          </td>
          <td>
            <%= link_to 'Update', edit_song_path(song) %>
          </td>
          <td>
            <%= link_to 'Delete', song_path(song), method: :delete %>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

  <div class='row'>
    <%= link_to 'Create Song', new_album_song_path(@album), class: 'btn btn-primary' %>
  </div>

</div>