config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  root 'dashboard#index'

  resources :artists, shallow: true do
    resources :albums
  end

  resources :albums, only: [], shallow: true do
    resources :songs
  end

  resources :songs do
    member do
      post :upvote
      post :downvote
    end
  end

end

app/views/layouts/_main.html.erb
<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to 'Rap Review', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Artists', artists_path %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li class='navbar-text'><%= current_user.email %></li>
          <li class='round-image-50'><%= image_tag(current_user.avatar.url(:thumb)) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rap Review</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <%= render 'layouts/main' %>
</body>
</html>